# Master Anatomical Scaffolder (Level 5)
# Rebuilds the framework skeleton and bridge chain for the canonical repo.

$Root = "c:/Users/antho/.gemini"
Set-Location $Root

Write-Host "--- Starting Definitive Scaffolding ---" -ForegroundColor Cyan

# 1. Root topology
Write-Host "Realignment of bridge folders..."
if (Test-Path ".gemini/.agents") {
    Move-Item -Path ".gemini/.agents" -Destination "." -Force
} else {
    New-Item -ItemType Directory -Path ".agents" -Force | Out-Null
}

# 2. Operational layers
$Ops = @("MEMORY", "SKILLS", "WORKFLOWS", "MCP", "EVALUATION", "SECURITY", "DOCS", "REGISTRY")
foreach ($op in $Ops) {
    New-Item -ItemType Directory -Path "BODY/$op" -Force | Out-Null
}

# 3. Recursive organ scaffolding
$Tree = @(
    "BODY/BRAIN/ORCHESTRATION", "BODY/BRAIN/SUBAGENTS", "BODY/BRAIN/MODELS", "BODY/BRAIN/ROUTING", "BODY/BRAIN/SKILLS", "BODY/BRAIN/WORKFLOWS", "BODY/BRAIN/TOOLS", "BODY/BRAIN/SCRIPTS", "BODY/BRAIN/TEMPLATES",
    "BODY/EYES/LEFT/RESEARCH", "BODY/EYES/RIGHT/VERIFICATION", "BODY/EYES/SOURCES", "BODY/EYES/CITATIONS", "BODY/EYES/SKILLS", "BODY/EYES/WORKFLOWS", "BODY/EYES/TOOLS", "BODY/EYES/SCRIPTS",
    "BODY/EARS/LEFT/USER_INPUT", "BODY/EARS/RIGHT/HOST_SIGNALS", "BODY/EARS/CONVERSATIONS", "BODY/EARS/TRANSCRIPTS", "BODY/EARS/SESSION_DIGESTS", "BODY/EARS/SKILLS", "BODY/EARS/WORKFLOWS", "BODY/EARS/TOOLS", "BODY/EARS/SCRIPTS",
    "BODY/NOSE/DETECTION", "BODY/NOSE/FILTERS", "BODY/NOSE/PROMPT_INJECTION", "BODY/NOSE/HALLUCINATION_SIGNALS", "BODY/NOSE/SKILLS", "BODY/NOSE/WORKFLOWS", "BODY/NOSE/TOOLS", "BODY/NOSE/SCRIPTS",
    "BODY/MOUTH/INTERFACE", "BODY/MOUTH/RESPONSES", "BODY/MOUTH/ADAPTERS", "BODY/MOUTH/COMMANDS", "BODY/MOUTH/SKILLS", "BODY/MOUTH/WORKFLOWS", "BODY/MOUTH/TOOLS", "BODY/MOUTH/SCRIPTS", "BODY/MOUTH/TEMPLATES",
    "BODY/HANDS/LEFT/DRAFTING", "BODY/HANDS/RIGHT/EXECUTION", "BODY/HANDS/PATCH_PLANS", "BODY/HANDS/COMMANDS", "BODY/HANDS/SKILLS", "BODY/HANDS/WORKFLOWS", "BODY/HANDS/TOOLS", "BODY/HANDS/SCRIPTS",
    "BODY/HEART/VALUES", "BODY/HEART/USER_PREFERENCES", "BODY/HEART/DECISIONS", "BODY/HEART/GOVERNANCE", "BODY/HEART/POLICIES", "BODY/HEART/SKILLS", "BODY/HEART/WORKFLOWS", "BODY/HEART/TOOLS", "BODY/HEART/SCRIPTS",
    "BODY/NERVES/MCP/SERVERS", "BODY/NERVES/CONNECTIONS", "BODY/NERVES/OPENROUTER", "BODY/NERVES/MODEL_ROTATION", "BODY/NERVES/RATE_LIMITS", "BODY/NERVES/FREE_TIER_ROUTING", "BODY/NERVES/SKILLS", "BODY/NERVES/WORKFLOWS", "BODY/NERVES/TOOLS", "BODY/NERVES/SCRIPTS",
    "BODY/ORGANS/MEMORY", "BODY/ORGANS/SKILLS", "BODY/ORGANS/WORKFLOWS", "BODY/ORGANS/TOOLS", "BODY/ORGANS/SCRIPTS",
    "BODY/IMMUNE/SECURITY", "BODY/IMMUNE/PRIVACY", "BODY/IMMUNE/SECRETS", "BODY/IMMUNE/GUARDRAILS", "BODY/IMMUNE/SUPPLY_CHAIN", "BODY/IMMUNE/SKILLS", "BODY/IMMUNE/WORKFLOWS", "BODY/IMMUNE/TOOLS", "BODY/IMMUNE/SCRIPTS",
    "BODY/SKELETON/BONES/DOCS/ORIGIN", "BODY/SKELETON/BONES/DOCS/PROMOTED", "BODY/SKELETON/BONES/LOGS", "BODY/SKELETON/STRUCTURE", "BODY/SKELETON/SCHEMAS", "BODY/SKELETON/TEMPLATES", "BODY/SKELETON/MANIFESTS", "BODY/SKELETON/SKILLS", "BODY/SKELETON/WORKFLOWS", "BODY/SKELETON/TOOLS", "BODY/SKELETON/SCRIPTS",
    "BODY/LEGS/ENVIRONMENTS", "BODY/LEGS/PROJECTS", "BODY/LEGS/DEPLOYMENT", "BODY/LEGS/WORKTREES", "BODY/LEGS/SKILLS", "BODY/LEGS/WORKFLOWS", "BODY/LEGS/TOOLS", "BODY/LEGS/SCRIPTS"
)

foreach ($folder in $Tree) {
    if (-not (Test-Path $folder)) {
        New-Item -ItemType Directory -Path $folder -Force | Out-Null
    }
}

# 4. Master bridge chain
Write-Host "Creating bridge chain..."
$Instr = @"
# Master Instructions
@../BODY/SKELETON/BOOT.md
@../BODY/HEART/POLICIES/OPERATING_PRINCIPLES.md
@../BODY/BRAIN/ORCHESTRATION/CURRENT_STATE.md
@../BODY/BRAIN/ORCHESTRATION/ACTIVE_PLAN.md
@../BODY/SKELETON/STRUCTURE/BODY_MAP.md
"@
Set-Content -Path ".agents/instructions.md" -Value $Instr

$GeminiMD = @"
---
title: Global Gemini Instructions
description: Entry-point for Gemini CLI and Antigravity. Imports project instructions.
---
@../.agents/instructions.md
"@
Set-Content -Path ".gemini/GEMINI.md" -Value $GeminiMD

$AgentsMD = @"
This project is governed by BODY.
Read BODY/SKELETON/BOOT.md first.
"@
Set-Content -Path "AGENTS.md" -Value $AgentsMD

Write-Host "--- Alignment achieved ---" -ForegroundColor Green
